### ISSUE TITLE
How can i decompile MC 1.14.4

### ISSUE THREAD

**Issue by Finnlife** [hypercubemc-github/Modern-Minecraft-Decompiler#12]
How can i decompile MC 1.14.4 in the Decompiler?
I cant find the setting in the build.gradle.

**Comment by ahmed605** [comment]
Edit these lines:
https://github.com/hypercubemc-github/Modern-Minecraft-Decompiler/blob/c5884130a02de96b40e7d2be05b81b289e1368d4/build.gradle#L22

https://github.com/hypercubemc-github/Modern-Minecraft-Decompiler/blob/c5884130a02de96b40e7d2be05b81b289e1368d4/build.gradle#L39

https://github.com/hypercubemc-github/Modern-Minecraft-Decompiler/blob/c5884130a02de96b40e7d2be05b81b289e1368d4/build.gradle#L40

https://github.com/hypercubemc-github/Modern-Minecraft-Decompiler/blob/c5884130a02de96b40e7d2be05b81b289e1368d4/build.gradle#L55
