### ISSUE TITLE
Minecract cannot obtain the narrator library

### ISSUE THREAD

**Issue by f1nniboy** [hypercubemc-github/Modern-Minecraft-Decompiler#13]
Minecraft cannot obtain the narrator library:
ERROR : Couldn't load Narrator library : Unable to load library 'SAPIWrapper_x86': Can't obtain InputStream for win32-x86-64/SAPIWrapper_x86.dll

**Comment by ahmed605** [comment]
What's the OS and processor architecture?

**Comment by f1nniboy** [comment]
Windows 10 and 64 bit

**Comment by ahmed605** [comment]
Try running Gradle task genIntellijRuns and then do this: https://github.com/hypercubemc-github/Modern-Minecraft-Decompiler/wiki/Running-the-Client-in-the-IDE#method-3--not-recommended-

**Comment by ahmed605** [comment]
@f1nniboy does that fixed your issue ⤵️

> Try running Gradle task genIntellijRuns and then do this: https://github.com/hypercubemc-github/Modern-Minecraft-Decompiler/wiki/Running-the-Client-in-the-IDE#method-3--not-recommended-
