### ISSUE TITLE
reobfJar not re-obfuscating source code

### ISSUE THREAD

**Issue by xJoyride** [hypercubemc-github/Modern-Minecraft-Decompiler#15]
MCD -> tasks -> other -> reobfJar doesn't re-obfuscate the source code.

Side note: thank you so much for this project, I used to use MCP back in 1.6. When I came back to the game in 1.15, I found MCP didn't release their mod pack anymore and was devastated. I tried forge and didn't like it, so when I found this project I was overjoyed. 
TLDR: Thank you so much for this!

[log.txt](https://github.com/hypercubemc-github/Modern-Minecraft-Decompiler/files/4250413/log.txt)
![Capture](https://user-images.githubusercontent.com/13449002/75255958-ba3bd280-581d-11ea-97db-8cb575b8a16d.PNG)

Loading mappings
0 packages, 5137 classes, 18825 fields, 34159 methods
Remapping final jar
Filtered: META-INF/
Filtered: META-INF/MANIFEST.MF
Filtered: com/
Filtered: com/mojang/
Filtered: com/mojang/blaze3d/
Filtered: com/mojang/blaze3d/matrix/
Filtered: com/mojang/blaze3d/platform/
Filtered: com/mojang/blaze3d/systems/
Filtered: com/mojang/blaze3d/vertex/
etc...

**Comment by xJoyride** [comment]
Also, if I can get this working, I'd be happy to fill out the wiki for you.

**Comment by ahmed605** [comment]
Yes, I have noticed that also but that's on MCPConfig side not on our side

**Comment by xJoyride** [comment]
The jar from the gradle build can't be run, correct? Even with the assets, data, pack.mcmeta, and pack.png copied from the orginal jar, I still can't get it to run. I tried:

- running it with the command line (with u/n and p/w)
- with the launcher (added new installation pointing to modded directory)
- double clicking on it

Is there any way to play what I've created outside the IDE? Like the good old MCP days?

**Comment by ahmed605** [comment]
@xJoyride you can play it, delete META-INF from the jar --> Copy all assets and data (with:pack.mcmeta and pack.png) to the jar --> create a JSON file for the jar (for the launcher) without hashes and file sizes (or change them (SHA, file sizes, download urls)) and change the required things in the JSON file

**Comment by xJoyride** [comment]
@ahmed605 You're a hero and a saint. Thank you so much Ahmed, I'm blown away by your generosity to a stranger. Thank you!

**Comment by ahmed605** [comment]
You're welcome 😊

**Comment by ahmed605** [comment]
@xJoyride thank you very much for the Wiki page, it's very beautiful and well written 👍👌

**Comment by xJoyride** [comment]
Happy to help!
