### ISSUE TITLE
This is not a Decompiler, nor is it "Based on: ForgeGradle"

### ISSUE THREAD

**Issue by LexManos** [hypercubemc-github/Modern-Minecraft-Decompiler#2]
This is a small buildscript that uses https://github.com/MinecraftForge/ForgeGradle
If you want to use a system that is sane, and actually knows what it is doing. Feel free to use FG yourself. You do not need this buildscript and whatever else he bundles with it.

**Comment by ahmed605** [comment]
@LexManos I archived my one this rebo is not my own

**Comment by ahmed605** [comment]
BTW it's legal

**Comment by Justsnoopy30** [comment]
Oh, of course, Lex finds this. 🙄

**Comment by ahmed605** [comment]
@LexManos One question why you hate us LOL

**Comment by Justsnoopy30** [comment]
He always will.

**Comment by LexManos** [comment]
I do not hate you, I think you are a couple of kids who need to learn what you're doing and do things correctly.

**Comment by ahmed605** [comment]
@LexManos Look at this commit https://github.com/hypercubemc-github/Modern-Minecraft-Decompiler/commit/da452a36e1acfcbcc8b7c7c6a5b31921733fcec0 are you happy now
