### ISSUE TITLE
Minecraft wont load the modded jar for the life of it

### ISSUE THREAD

**Issue by ghost** [hypercubemc-github/Modern-Minecraft-Decompiler#26]
I tried everything, followed all needed steps, copied, modified, etc. But the launcher just wont launch the modded jar. It always downloads the official one before running. How can I fix this?

**Comment by Justsnoopy30** [comment]
Remove server hash in the version json.

**Comment by ghost** [comment]
> Remove server hash in the version json.

I removed every hash and size property needed, as described in the wiki. It still wont run the modified jarfile, but download a new one.

**Comment by Justsnoopy30** [comment]
Are you sure you are launching the modified version in your launcher, and that you restarted your launcher after adding the folder, jar, and json in?

**Comment by ghost** [comment]
> Are you sure you are launching the modified version in your launcher, and that you restarted your launcher after adding the folder, jar, and json in?

I am absolutely sure I did

**Comment by ghost** [comment]
@Justsnoopy30

**Comment by ghost** [comment]
It also doesnt seem to reobfuscate the jar, maybe that's the issue

**Comment by Justsnoopy30** [comment]
Huh, strange. Well I don't know what to tell you, I don't use this myself anymore. If you want to mod minecraft the proper way, try [fabric](https://fabricmc.net).

**Comment by ghost** [comment]
Update: I got it working, but it just exits with error code 0 now.

**Comment by ghost** [comment]
Update 2: finally works as it should, runs kind of smoothly.
