### ISSUE TITLE
Legal

### ISSUE THREAD

**Issue by Earthcomputer** [hypercubemc-github/Modern-Minecraft-Decompiler#3]
Is this even legal to use the MCP-Config in this way? Since it's licence says something else.
Read this thread on Discord: [here](https://discordapp.com/channels/313125603924639766/570666026077913098/593632955922907137)

He does not like that you do it this way.

**Comment by Earthcomputer** [comment]
Ah looks like lex beat me to it.

**Comment by ahmed605** [comment]
@Earthcomputer now it's 100% legal I removed maven repos that have MCPconfig and this doesn't has MCPconfig at all
