### ISSUE TITLE
How can i compile?

### ISSUE THREAD

**Issue by Muharrem-Yildirim** [hypercubemc-github/Modern-Minecraft-Decompiler#4]
Hello, how can i compile code?

**Comment by Justsnoopy30** [comment]
Into a jar file?

**Comment by Muharrem-Yildirim** [comment]
yes

**Comment by Justsnoopy30** [comment]
I'm not home right now so I cannot check, but I think it is a Gradle task setup. You know you cannot modify it and put it into a jar file, only you can use it and it cannot be distributed/shared, right?

**Comment by Muharrem-Yildirim** [comment]
I want my own anti-cheat launcher like https://sonoyuncu.network So I need to edit client

**Comment by Justsnoopy30** [comment]
"WHAT IS SONOYUNCU NETWORK ?
SonOyuncu Network LogoSonoyunc Network 7 years serving is Turkey's oldest Minecraft server. ***With SonOyuncu Launcher you can play Minecraft for free.***"
That has nothing to do with anti-cheat. That's a cracked/pirated launcher.
Explain?

**Comment by Justsnoopy30** [comment]
@leideeen above ^^^^^^^

**Comment by Muharrem-Yildirim** [comment]
http://prntscr.com/osaswv They have a system when you connect with another client it gives that error i want to create launcher like this

**Comment by Muharrem-Yildirim** [comment]
https://www.google.com/search?q=sonoyuncu+launcher&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjEnKu354DkAhVMz6YKHWAuD2gQ_AUIESgB&biw=1920&bih=937#imgrc=sSAvkVt-_Lo4dM:

**Comment by Justsnoopy30** [comment]
Just got home, sorry for delay.

**Comment by Justsnoopy30** [comment]
You're not distributing this, right? Only you're using it?

**Comment by Muharrem-Yildirim** [comment]
I will share it only with my players and they can only joiin my server

**Comment by Justsnoopy30** [comment]
X 
You can't share it with **ANYBODY**. It is illegal to share a directly modified Minecraft client.

**Comment by Muharrem-Yildirim** [comment]
Is there any method to make client-sided anticheat i really need it
since 3-4 days im working about that

**Comment by Justsnoopy30** [comment]
Why not just a server side anti-cheat?

**Comment by Muharrem-Yildirim** [comment]
server side checks aren't enough some players still hacking

**Comment by Justsnoopy30** [comment]
@leideeen Get a better anti cheat. Try NoCheatPlus if you have a spigot server.

**Comment by Muharrem-Yildirim** [comment]
Already i tried too many anti cheats thanks anyway

**Comment by ahmed605** [comment]
@Justsnoopy30 Sharing a modified Minecraft client (Without sharing SRC) is legal (if it doesn't break Minecraft legal rights (Terms of use)) but remember I mean sharing not distribution (I mean not for commercial use)
