### ISSUE TITLE
Cant create  release .jar

### ISSUE THREAD

**Issue by Pfuenzle** [hypercubemc-github/Modern-Minecraft-Decompiler#5]
It seems like Im not able to create a release build. Everytime i run the grade script (other -> release), I get the error: 

* What went wrong:
A problem was found with the configuration of task ':applyRangeMap'.
> File 'C:\Users\user\Desktop\DrehCraft\1.14\build\extractRangeMap\output.txt' specified for property 'rangeMap' does not exist.

Additionally, how am I able to get an obfuscated .jar/the obfuscated classes? After running other -> reobfJar, the only thing in the build/reobfJar folder is an output.jar, which is what it seems just the original .jar from minecraft. When i look into the log.txt it says that the folders where my mod should be got filtered

> Filtered: io/pfuenzle/

Also, when running build -> jar, only the edited minecraft classes are placed in build/classes. It creates (sub)folders for my package name but doesnt place anything in them, but the mod works fine when Im just running it with IntelliJ

**Comment by ahmed605** [comment]
Run Build task from MCD not others not release

**Comment by Pfuenzle** [comment]
Thanks, now I got a jar with my code.
But is there a way to reobfuscate it so I can drop the modified classes in a vanilla .jar?

**Comment by Justsnoopy30** [comment]
You're not distributing this are you?

**Comment by Pfuenzle** [comment]
Is this forbidden? I understood 

> WARNING: You CAN'T publish any code generated by this tool

as the code that is generated by it, not the compiled classes

**Comment by Justsnoopy30** [comment]
Oh, I get what you mean now, that is fine.

**Comment by Justsnoopy30** [comment]
I'm not home right now, so I can't check, but I think there is a task to reobfusticate.

**Comment by Justsnoopy30** [comment]
Will find it when home.

**Comment by Pfuenzle** [comment]
Did you find it? Or did reobfJar work for you?

**Comment by Justsnoopy30** [comment]
Sorry rly busy, maybe this afternoon. I'm gonna close this because you created the jar and that's what the issue was about.
