### ISSUE TITLE
Official Minecraft Obfuscation Maps Released

### ISSUE THREAD

**Issue by Justsnoopy30** [hypercubemc-github/Modern-Minecraft-Decompiler#6]
Read here: https://www.minecraft.net/en-us/article/minecraft-snapshot-19w36a
Official Minecraft Obfuscation Maps Released (for latest snapshot and 1.14.4)
It does not unobfustcate param names. Is it possible to switch this script to the official Obfuscation mapping and use the param names in forgegradle?
Notify - @ahmed605

**Comment by Pfuenzle** [comment]
From what I read, the official mappings dont include parameter/variable namings and javadoc, so I dont know if it will be very effective

**Comment by ahmed605** [comment]
where can this be downloaded if that in CSV format also I can make my own Perfect Minecraft Decompiler

**Comment by Justsnoopy30** [comment]
Not csv, .txt, I heard it might be "proguard" format.

**Comment by Pfuenzle** [comment]
Yes its in the proguard format, here ist the mapping of the snapshot

https://launcher.mojang.com/v1/objects/a981dbf4095dbb2ffb078db14d676fb8f9c2fa99/client.txt

**Comment by ahmed605** [comment]
so it can be easily deobfuscated using this tool https://github.com/FireMasterK/SkidSuite2-Latest or similar tools

**Comment by Pfuenzle** [comment]
Do you know any tools similar to skidsuite? I tried to use it but the remapper doesn't seem to accept the mappings.txt

**Comment by ahmed605** [comment]
@Pfuenzle I think Forge Remapper https://github.com/MinecraftForge/Remapper now supports proguard format

**Comment by ahmed605** [comment]
Also there's a MC decompiler uses the new mappings (I think also FernFlower supports this mappings type) https://github.com/hube12/DecompilerMC/

**Comment by Justsnoopy30** [comment]
https://github.com/hube12/DecompilerMC/ looks good, when I have time, I'll try that.

**Comment by Justsnoopy30** [comment]
Tried https://github.com/hube12/DecompilerMC/, it works great and decompiles MC, but currently, it cannot be recompiled but that is being worked on. Issue closed.
