### ISSUE TITLE
Compiler error regarding net.minecraftforge.api.distmarker.

### ISSUE THREAD

**Issue by MajickTek** [hypercubemc-github/Modern-Minecraft-Decompiler#7]
there are hundreds upon hundreds of errors while compiling complaining that net.minecraftforge.api.distmarker doesn't exist. Thus is part of Forge's API package, which I tried compiling but its gradle didn't work.

Unfortunately I can't give the log but for the most part it was:
~~~~
error: package net.minecraftforge.api.distmarker does not exist
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.api.distmarker.OnlyIns;
~~~~

**Comment by ahmed605** [comment]
try after this commit https://github.com/hypercubemc-github/Modern-Minecraft-Decompiler/commit/e63a04a0ed6e1518d3c46a60caf87deeb7ef4cc1

**Comment by Justsnoopy30** [comment]
No comments on this issue for 7 days, and @ahmed605 responded, so issue closed.

**Comment by MajickTek** [comment]
Confirmed the issue has been solved! Thanks alot! no more manually patching mcp >:]
