### ISSUE TITLE
Compiling to Jar File

### ISSUE THREAD

**Issue by Justsnoopy30** [hypercubemc-github/Modern-Minecraft-Decompiler#8]
@ahmed605 How do you compile this into a jar file again?

**Comment by ahmed605** [comment]
run Build task

**Comment by Justsnoopy30** [comment]
Where exactly in the Gradle tasks is it?

**Comment by ahmed605** [comment]
run MCD -> MCD -> Tasks -> Build -> Build then the release jar will be in the "build/libs/"

**Comment by Justsnoopy30** [comment]
@ahmed605 Crashing on launch

**Comment by ahmed605** [comment]
the log?

**Comment by Justsnoopy30** [comment]
Short Error:
> The game crashed whilst initializing game
Error: java.lang.NullPointerException: "in" is null!

**Comment by Justsnoopy30** [comment]
@ahmed605

**Comment by Justsnoopy30** [comment]
Full Error:
https://pastebin.com/SUDgYZ2n

**Comment by Justsnoopy30** [comment]
Will be gone for about 8 hours. Cya

**Comment by Justsnoopy30** [comment]
Here now @ahmed605  , when are you gonna be online?

**Comment by Justsnoopy30** [comment]
@ahmed605

**Comment by Justsnoopy30** [comment]
@ahmed605

**Comment by ahmed605** [comment]
try to build another jar and but assets and data to it without deleting META-INF

**Comment by Justsnoopy30** [comment]
Will try, my IntelliJ is starting up.

**Comment by Justsnoopy30** [comment]
@ahmed605 Didn't work, same error.

**Comment by Justsnoopy30** [comment]
But I opened up MANIEFEST.MF in META-INF and it only contains 1 line: Manifest-Version: 1.0

**Comment by Justsnoopy30** [comment]
Also, I noticed 

> Missing version information!

in the log.

**Comment by ahmed605** [comment]
Did you created the json or used the original one without changes

**Comment by Justsnoopy30** [comment]
Copied 1.14.4.json and removed download, Sha, and size of jar.

**Comment by Justsnoopy30** [comment]
I think it might have to do with MethodsReturnNotNull.class in mcp folder, maybe it is not working because looking at the error log shows methods are returning null.

**Comment by Justsnoopy30** [comment]
Aha! I think I finally figured out the entire issue, testing...

**Comment by Justsnoopy30** [comment]
Nope, that didn't work, in the json file I tried changing the line that said `mainClass:net.minecraft.main.Main` to `mainClass:mcp.client.Start` and now it crashes with this:
> Exception in thread "main" joptsimple.MultipleArgumentsForOptionException: Found multiple arguments for option version, but you asked for only one
	at joptsimple.OptionSet.valueOf(OptionSet.java:179)
	at net.minecraft.client.main.Main.getValue(Main.java:134)
	at net.minecraft.client.main.Main.main(Main.java:96)
	at mcp.client.Start.main(Start.java:17)

**Comment by Justsnoopy30** [comment]
@ahmed605

**Comment by Justsnoopy30** [comment]
@ahmed605 When are you ever gonna respond...?

**Comment by ahmed605** [comment]
Sorry I'm very busy this error because the arguments of jar and JRE system is not correct so copy the arguments from mcd from your IDE

**Comment by Justsnoopy30** [comment]
Oh ok. But wait, it's a Friday, how can you be busy on a friday? :P

**Comment by Justsnoopy30** [comment]
Also, I figured out the issue. I tested a modified version of mcp that works past 1.13+ and guess what, I got the exact same error. The mcp_snapshot is 1.14.3 and hasn't been updated to 1.14.4 (maybe because of officially released obfuscation maps?) and when 1.14.4 came, of course, there were code changes, and since mcp_snapshot is still 1.14.3, they don't match up right, and hence, our error.

**Comment by Justsnoopy30** [comment]
Nope, nevermind, it is not that either, tried 1.14.3 and same.

**Comment by Justsnoopy30** [comment]
OMG I FEEL SO STUPID. I solved the issue. Apparently, when adding in the assets and data folders from the official jar, there is a pack.mcmeta and pack.png hidden in at the bottom with the rest of the obfuscated class files, and I needed to add that to my jar.

**Comment by ahmed605** [comment]
You're NOT stupid this is a small error that can happen to anyone BTW I replied to you on Friday because I'm not busy on Friday but I'm very busy on other week days because of school

**Comment by Justsnoopy30** [comment]
Ok.
I'm gonna add this to the wiki in case someone else has the same problem.

**Comment by Justsnoopy30** [comment]
(Soon)
