### ISSUE TITLE
Problem with the assets

### ISSUE THREAD

**Issue by MrToLegit** [hypercubemc-github/Modern-Minecraft-Decompiler#9]
I have a problem with this tool. My problem is that I can't include my own assets files. I tried everything. If I don't use the standard textures it always show me the default texture.

Here is the error:
https://pastebin.com/Utw3eY6d

**Comment by ahmed605** [comment]
The error says that background.png is not found in the jar file

**Comment by MrToLegit** [comment]
Yes but I think its because the client can not find the file in the assets folder. So i created a package named 'assets.minecraft.textures' and added there my file. But when I start the client it show this error anyway.

**Comment by MrToLegit** [comment]
I want to draw a custom background on the MainMenuScreen. So i created a method https://pastebin.com/pcfH2wP8 and this method works because it shows the texture when minecraft misses a texture.
And in the render method from minecraft i execute:
`drawTextureAt(new ResourceLocation("textures/background.png"));`

I think that the client don't uses my assets folder that I created in src/main/java

And in MCP 1.8.8 it worked.

**Comment by MrToLegit** [comment]
It look like it works.
I just switched to eclipse.

**Comment by Justsnoopy30** [comment]
Just noticed this and then it said closed 30 seconds ago, lol.

**Comment by MrToLegit** [comment]
:)
